# Default values for testunited-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

core:
  containerPort: 80
  service:
    port: 80
    name: core
webui:
  containerPort: 80
  service:
    port: 80
    name: webui