# Default values for testunited-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  registry: registry.minikube.local:80
  namespace: testunited

core:
  service:
    type: ClusterIP
  ingress:
    hostname: testunited.minikube.local