apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Values.env.namespace }}
  name: core
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: {{ .Values.env.host }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: {{ .Values.core.service.name }}
          servicePort: {{ .Values.core.service.port }}