apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.env.namespace }}
  name: webapi
  labels:
    app: webapi
spec:
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: {{ .Values.images.webapi }}
        env:
        - name: server.port
          value: "{{ .Values.webapi.containerPort }}"
        - name: spring.jpa.hibernate.ddl-auto
          value: "none"
        - name: spring.datasource.url
          value: "jdbc:mysql://mysql:3306/testunited"
        - name: spring.datasource.username
          value: "springuser"
        - name: spring.datasource.password
          value: "testunited_spring"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.webapi.containerPort }}