apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: webapi
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: web-api.{{ .Values.env.host }}
    http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.webapi.service.name }}
            port:
              number: {{ .Values.webapi.service.port }}