apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.env.namespace }}
  name: webapi
spec:
  type: {{ .Values.webapi.service.type }}
  selector:
    app: webapi
  ports:
  - protocol: TCP
    port: {{ .Values.webapi.service.port }}
    targetPort: {{ .Values.webapi.containerPort }}
