apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: webui
  labels:
    app: webui
spec:
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - name: webui
        image: {{ .Values.images.webui }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.webui.containerPort }}