apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: webui
spec:
  type: {{ .Values.webui.service.type }}
  selector:
    app: webui
  ports:
  - protocol: TCP
    port: {{ .Values.webui.service.port }}
    targetPort: {{ .Values.webui.containerPort }}
