apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.env.namespace }}
  name: webui
spec:
  type: {{ .Values.core.service.type }}
  selector:
    app: webui
  ports:
  - protocol: TCP
    port: {{ .Values.core.service.port }}
    targetPort: {{ .Values.core.containerPort }}
