apiVersion: v1
kind: Service
metadata:
  namespace: testunited
  name: core
spec:
  type: {{ .Values.core.service.type }}
  selector:
    app: core
  ports:
  - protocol: TCP
    port: {{ .Values.core.service.port }}
    targetPort: {{ .Values.core.containerPort }}
